#include<fstream.h>
#include<conio.h>
#include<stdio.h>
#include<string.h>
#include<process.h>
#include<stdlib.h>
#include<ctype.h>
classtel
{
charname[50],city[50],add[81],occ[81];
charnum1[11],num2[11],num3[11];
public:
voidinsert()
{
charch;
cout<<"\nENTERTHEFOLLWINGINFORMATION ";
cout<<"\nNAME";
gets(name);
cout<<"\nCITY";
gets(city);
cout<<"\nOCCUPATION ";
gets(occ);
cout<<"\nADDRESS";
gets(add);
cout<<"\nNUMBER1";
gets(num1);
cout<<"\nYOUWANTSTOENTEROTHERNUMBER(pressY)";cin>>ch;
if(ch=='Y'||ch=='y')
{
cout<<"\nNUMBER2";
gets(num2);
cout<<"\nYOUWANTSTOENTEROTHERNUMBER(pressY)";cin>>ch;
if(ch=='Y'||ch=='y')
{
cout<<"\nNUMBER3";
gets(num3);
}
else
{
strcpy(num3,"");
}
}
else
{
strcpy(num2,"");
strcpy(num3,"");
}
}
voiddisplay()
{
cout<<"\nTHEFOLLWINGISTHEDETAILOFPERSON";
cout<<"\nNAME"<<name;
cout<<"\nCITY"<<city;
cout<<"\nOCCUPATION"<<occ;
cout<<"\nADDRESS"<<add;
cout<<"\nNUMBER1"<<num1<<"\nNUMBER2"<<num2;cout<<"\nNUMBER3"<<num3;
}
char*fnam()
{
return(name);
}
char*fnum1()
{
return(num1);
}
char*fnum2()
{
return(num2);
}
char*fnum3()
{
return(num3);
}
};
voidsername();
voidsernum();
voiddelet();
voidsername()
{
inti=0;
charstr[50];
tele1;
cout<<"\nEnterNameofperson";
gets(str);
fstreamfin("tel.dat",ios::binary|ios::in);
if(!fin)
{
cout<<"\nI\OError";
}
else
{
while(fin.read((char*)&e1,sizeof(e1)))
{
cout<<"inwhile";
if(strcmpi(e1.fnam(),str)==0)
{
//cout<<"inwhile";
i++;
e1.display();
}
}
if(i==0)
cout<<"\nPERSONNAMEISNOTINLIST";fin.close();
getch();
}
}
voiddisprec()
{
tele1;
inti=0;
fstreamfin("tel.dat",ios::binary|ios::in);
if(!fin)
{
cout<<"\nI\OError";
}
else
{
while(fin.read((char*)&e1,sizeof(e1)))
{
i++;
e1.display();
getch();
}
if(i==0)
{
cout<<"\nNoData";
getch();
}
fin.close();
}
}
voidsernum()
{
inti,k=0;
fstreamfin("tel.dat",ios::binary|ios::in);
if(!fin)
{
cout<<"\nI\OError";
}
else
{
charstr1[50];
cout<<"\nEnterNUMBERtobesearch";cin>>str1;
tele1;
while(fin.read((char*)&e1,sizeof(e1)))
{
if(strcmpi(e1.fnum1(),str1)==0||strcmpi(e1.fnum2(),str1)==0||strcmpi(e1.fnum3(),str1)==0)
{
k++;
e1.display();
break;
}
}
if(k==0)
cout<<"\nPERSONNUMBERISNOTINLIST";fin.close();
}
}
voiddelet()
{
inti;
fstreamfin("tel.dat",ios::binary|ios::in);
fstreamfig("tel1.dat",ios::binary|ios::out);
if(!fin)
{
cout<<"\nI\OError";
}
else
{
intj=0;
charstr[50],op;
tele1;
cout<<"\nEnterNamewhoserecordtoberemoved:";
gets(str);
while(fin.read((char*)&e1,sizeof(e1)))
{
intk;
j++;
if(strcmpi(str,e1.fnam())==0)
{
i++;
e1.display();
cout<<"\nDoyouwanttodeleteit";cin>>op;
if(toupper(op)=='Y')
cout<<"\nRECORDDELETED";else
fig.write((char*)&e1,sizeof(e1));}
else
fig.write((char*)&e1,sizeof(e1));}
if(i==0)
cout<<"\nPERSONNAMEISNOTINLIST";fin.close();
fig.close();
remove("tel.dat");
rename("tel1.dat","tel.dat");
}
}
voidinsert1()
{
tele1;
fstreamfin("tel.dat",ios::binary|ios::app);
if(!fin)
{
cout<<"\nI\OError";
}
else
{
e1.insert();
fin.write((char*)&e1,sizeof(e1));
fin.close();
}
}
intrecmain()
{
charch;
while(1)
{
clrscr();
cout<<"\n\n\n\t\tRecordManagement";
cout<<"\n\t\t~~~~~~~~~~~~~~~~~";cout<<"\n\t1.InsertaRecord";
cout<<"\n\t2.DeleteaRecord";
cout<<"\n\t3.DisplayallRecords";
cout<<"\n\t4.back";
cout<<"\n\n\tEnterYourChoice";
cin>>ch;
switch(ch)
{
case'1':insert1();break;
case'2':delet();break;
case'3':disprec();break;
case'4':return0;
default:cout<<"\nInvalidchoice";}
getch();
}
}
intsearchmain()
{
charch;
while(1)
{
clrscr();
cout<<"\n\n\n\t\tSearchOperation";
cout<<"\n\t\t~~~~~~~~~~~~~~~~";
cout<<"\n\t1.ByName";
cout<<"\n\t2.ByNumber";
cout<<"\n\t3.back";
cout<<"\n\n\tEnterYourChoice";
cin>>ch;
switch(ch)
{
case'1':sername();break;
case'2':sernum();break;
case'3':return0;
default:cout<<"\nInvalidchoice";}
getch();
}
}
voidmain()
{
charch;
while(1)
{
clrscr();
cout<<"\n\n\n\t\tTelephoneDirectory";
cout<<"\n\t\t~~~~~~~~~~~~~~~~~~~~";cout<<"\n\t1.RecordManagement";
cout<<"\n\t2.SearchOperation";
cout<<"\n\t3.Exit";
cout<<"\n\n\tEnterYourChoice";
cin>>ch;
switch(ch)
{
case'1':recmain();break;
case'2':searchmain();break;
case'3':exit(0);
default:cout<<"\nInvalidchoice";}
getch();
}
}